server:
  port: 8000
  servlet:
    context-path: /produto-service
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
spring:
  application:
    name: produto-service
  profiles:
    active:
    - "test"
  jackson:
  # para não serializar objetos nulos 
    default-property-inclusion: NON_NULL
    serialization: 
      fail-on-empty-beans: false
    
springdoc:
  show-actuator: true
  api-docs:
    path: /v3/api-docs
    