erver:
  port: 8765
  servlet:
    context-path: /gateway
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          #lower-case-service-id: true
