server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods: "*"
    
      discovery:
        locator:
          enabled: true
         # lower-case-service-id: true
      routes:      
      - id: client-service
        uri: lb://client-service
        predicates:
        - Path=/client-service/**  
       
      - id: produto-service
        uri: lb://produto-service
        predicates:
        - Path=/produto-service/**
        
      - id: sales-service
        uri: lb://sales-service
        predicates:
        - Path=/sales-service/**
        
        
