server:
  port: 9000
  servlet:
    context-path: /sales-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
            
spring:
  application:
    name: sales-service
  datasource:    
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    ddl-auto: update
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect 
  jackson:
  # para não serializar objetos nulos 
    default-property-inclusion: NON_NULL
    serialization: 
      fail-on-empty-beans: false
      
  rabbitmq:
    connection-timeout: 5000
    host: localhost
    port: 5672
    username: nando.systempro@hotmail.com
    password: Fe2812
       
      
jwt:
  secret: secretkey
  expiration: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds