server:
  port: 7000
  servlet:
    context-path: /client-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
spring:
  application:
    name: client-service
  profiles:
    active:
    - "test"
  jackson:
  # para não serializar objetos nulos 
    default-property-inclusion: NON_NULL
    serialization: 
      fail-on-empty-beans: false
jwt:
  secret: secretkey
  expiration: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds
  
