server:
  port: 7000
  servlet:
    context-path: /client-service
spring:
  application:
    name: client-service
  datasource:    
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    ddl-auto: update
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect 
  jackson:
  # para não serializar objetos nulos 
    default-property-inclusion: NON_NULL
    serialization: 
      fail-on-empty-beans: false
