server:
  port: 7000
  servlet:
    context-path: /client-service
spring:
  application:
    name: client-service
  profiles:
    active:
    - "test"
  jackson:
  # para não serializar objetos nulos 
    default-property-inclusion: NON_NULL
    serialization: 
      fail-on-empty-beans: false
